#!/usr/bin/env bash

if [ ! -z "$REDISTOGO_URL" ]; then
  REDIS_URL="$REDISTOGO_URL"
fi

if [ "$USE_REDIS" == 1 ]; then
  exec pylivetrader run -f algo/$1 --storage-engine redis
else
  exec pylivetrader run -f algo/$1 --storage-engine file --statefile tmp/state/$1.pkl
fi
