#!/usr/bin/env bash

read -p "Heroku App Name: " APP_NAME
read -p "Algorithm File Name: " ALGO_NAME
read -s -p "Alpaca API Key (typing is hidden): " API_KEY
echo
read -s -p "Alpaca API Secret Key (typing is hidden): " API_SECRET
echo
read -p "Alpaca Paper Trading? (Y/n) " PAPER

if [ -z "$PAPER" ] || [ "$PAPER" -eq "y" ] || [ "$PAPER" -eq "Y" ]; then
  API_HOST="https://paper-api.alpaca.markets"
else
  API_HOST="https://api.alpaca.markets"
fi

echo "Checking heroku login..."
if [ -z "$(heroku auth:whoami)" ]; then
  heroku login
fi

echo "Configuring app..."
heroku stack:set -a $APP_NAME container
heroku config:set -a $APP_NAME "ALGO=$ALGO_NAME" "APCA_API_BASE_URL=$API_HOST" "APCA_API_KEY_ID=$API_KEY" "APCA_API_SECRET_KEY=$API_SECRET"

echo
echo "Please go to https://dashboard.heroku.com/apps/$APP_NAME/deploy/github"
echo "and click 'Deploy Branch' in the 'Manual deploy' section"
echo
echo "Waiting for deploy..."

while [ "$(heroku ps:scale -a $APP_NAME | awk -F= '/worker/{ print $2 }' | tr -d ':Free')" -ne 0 ]; do
  print '.'
  sleep 1
done

heroku ps:scale -a $APP_NAME 'worker=1'

echo "Congratulations! Your algorithm is running. To check it's logs run 'heroku logs --tail -a $APP_NAME'"
